name: meg
description: Meg is a simple, powerful, and extensible file server for remote objects and archives
version: 0.1.0-wip


executables:
  meg: 

environment:
  sdk: ^3.8.0

dependencies:
  archive: ^4.0.7
  args: ^2.7.0
  async: ^2.13.0
  aws_s3_api: ^2.0.0
  chunked_stream: ^1.4.2
  collection: ^1.19.1
  file: ^7.0.1
  logging: ^1.3.0
  mime: ^2.0.0
  neat_cache: ^2.0.4
  neat_periodic_task: ^2.0.1
  path: ^1.9.1
  shelf: ^1.4.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3

